CONFIG_PREEMPT=y
CONFIG_PREEMPT_RT_FULL=y
# CONFIG_DEBUG_PREEMPT is not set
# CONFIG_DEBUG_SPINLOCK is not set
# CONFIG_DEBUG_MUTEXES is not set
# CONFIG_DEBUG_LOCK_ALLOC is not set
# CONFIG_PROVE_LOCKING is not set
# CONFIG_DEBUG_RT_MUTEXES is not set
### CONFIG_SLAB not set and CONFIG_SLUB=y has to be set for the 3.10.6-rt3 patchset
# CONFIG_SLAB is not set
CONFIG_SLUB=y
